version: '3.1'

services:

  shippy-cli-consignment:
    build: ./client
    depends_on:
      - shippy-service-consignment

  shippy-service-consignment:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - user-service
      - shippy-service-vessel

  shippy-service-vessel:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  datastore:
      image: mongo
      ports:
        - 27017:27017

  user-service:
      build: ./user-service
      ports:
        - 50053:50051
      environment:
        MICRO_ADDRESS: ":50051"
        MICRO_REGISTRY: "mdns"
        DB_NAME: "postgres"
        DB_HOST: "database"
        DB_PORT: "5432"
        DB_USER: "postgres"
        DB_PASSWORD: "postgres"
      depends_on:
         - database

  database:
      image: postgres
      ports:
        - 5432:5432

#  nats:
#      image: nats
#      ports:
#        - 4222:4222

  user-cli:
      build: ./user-cli
      environment:
        MICRO_REGISTRY: "mdns"
      depends_on:
        - user-service

  email-service:
        build: ./email-service
        environment:
          MICRO_REGISTRY: "mdns"

  api:
      image: microhq/micro
      ports:
       - 8080:8080
      environment:
         MICRO_REGISTRY: "mdns"
      command: api --handler=rpc --address=:8080 --namespace=shippy



